config/routes.rb
Rails.application.routes.draw do

    resources :doctors
    resources :patients
    resources :appointments
    resources :sessions

  get "/logout", to: "sessions#destroy"

      root to: "doctors#index"

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
validates :patient_id, presence: true
validates :doctor_id, presence: true
validates :test_id, presence: true

 belongs_to :doctor
 belongs_to :patient
 belongs_to :test
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
has_many :appointments
end

app/models/patient.rb
class Patient < ActiveRecord::Base
has_many :appointments
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :password, presence: true
has_secure_password
end

app/models/test.rb
class Test < ActiveRecord::Base
 has_many :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

 helper_method :current_patient
 before_action :auth

  def auth
  	if current_patient
  	else 
  	redirect_to new_session_path
  	end
  end

  def current_patient
	Patient.find_by(id: session["patient_id"])
  end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

  def index
  	@appointments = Appointment.all
  end

  def show
	@patient = current_patient
  @appointment = Appointment.find_by(id: params["id"])
  end

  def new
    @appointment = Appointment.new
  end

  def create
	  appointment = Appointment.new(params["appointment"])
  	appointment.patient = current_patient
    appointment.save
    redirect_to patient_url(current_patient), notice: "Appointment created"
  end

  def edit
    @appointment = Appointment.find_by(id: params["id"])
  end

  def update
  	appointment = Appointment.find_by(id: params["id"])
  	appointment.update(params["appointment"])
  redirect_to patient_url(current_patient), notice: "Appointment updated"
  end

 def destroy
 	appointment = Appointment.find_by(id: params["id"])
 	appointment.destroy
 	redirect_to patient_url(current_patient), alert: "Appointment cancelled"
 end

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

skip_before_action :auth, only: [:index, :show]

  def index
  	@doctors = Doctor.all
  end

  def show
	@doctor = Doctor.find_by(id: params["id"])
  end

  def new
    @doctor = Doctor.new
  end

  def create
	Doctor.create(params["doctor"])
  	redirect_to doctors_url
  end

  def edit
  	@doctor = Doctor.find_by(id: params["id"])
  end

  def update
  	doctor = Doctor.find_by(id: params["id"])
  	doctor.update(params["doctor"])
  	redirect_to doctors_url
  end

 def destroy
 	doctor = Doctor.find_by(id: params["id"])
 	doctor.delete
 	redirect_to doctors_url
 end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

skip_before_action :auth, only: [:index, :show, :new, :create]

  def index
  	@patients = Patient.all
  end

  def show
	  @patient = Patient.find_by(id: params["id"])
  end

  def new
    @patient = Patient.new
  end

  def create
	  @patient = Patient.create(params["patient"])
  	if @patient.valid?
    redirect_to patients_url, notice: "User created"
    else
    render "new"
    end
  end

  def edit
  	@patient = Patient.find_by(id: params["id"])
  end

  def update
  	@patient = Patient.find_by(id: params["id"])
  	@patient.update(params["patient"])
  	redirect_to patients_url
  end

  def destroy
  	@patient = Patient.find_by(id: params["id"])
   	@patient.destroy
   	redirect_to patients_url
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
skip_before_action :auth
layout false

  def create
        @patient = Patient.find_by(email: params["email"])
      if @patient.present?
        #yes, user exists
        if @patient.authenticate(params["password"])
        session["patient_id"] = @patient.id
        redirect_to patient_url(@patient)
        else
          redirect_to new_session_url, alert: "Wrong password"
        end
      else
        #no user with that email
        redirect_to new_session_url, alert: "Wrong email"
      end

    # params["email"] => the email address
    # params["password"] => the password
    # Do authentication
    # Redirect to the root_path
    # Display a notice that login was either successful or unsuccessful
  end

  def destroy
    # Do sign-out
    session["patient_id"] = new_session_url
    redirect_to root_url, notice: "See ya later"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/appointments/_form.html.erb
<%= form_for @appointment do |form| %>
  
<div class="form-group">
    <%= form.label :doctor_id %>
    <%= form.collection_select(:doctor_id, Doctor.all, :id, :last_name) %>
  </div>

<div class="form-group">
    <%= form.label :test_id %>
    <%= form.collection_select(:test_id, Test.all, :id, :name) %>
  </div>

<div class="form-group">
    <%= form.label :date %>
    <%= form.date_field :date, class: "form-control" %>
  </div>

<div class="form-group">
    <%= form.label :time %>
    <%= form.time_field :time, class: "form-control" %>
  </div>

  <%= form.submit class: "btn btn-success" %>
<% end %>

app/views/appointments/edit.html.erb
<%= render "form" %>

app/views/appointments/index.html.erb
<h3 class="page-header">
  All Appointments
 </h3>

<div class="row">
	<% @appointments.each do |appointment| %>
		<div class="col-sm-6">
				<p><strong>Doctor:</strong> <%= appointment.doctor.first_name %> <%= appointment.doctor.last_name %></p>
				<p><strong>Patient:</strong> <%= appointment.patient.first_name %> <%= appointment.patient.last_name %></p>
				<p><strong>Test:</strong> <%= appointment.test.name %></p>
					<%= link_to "Edit", edit_appointment_url(appointment), class: 'btn-sm btn-danger' %>
					<%= link_to "Delete", appointment_url(appointment), method: :delete, class: 'btn-sm btn-danger', data: {confirm: 'Seriously?'} %>
					<br><br>
		</div>
	<% end %>
</div>

app/views/appointments/new.html.erb
<%= render "form" %>

app/views/appointments/show.html.erb
<div class="row">
  <div class="col-md-6 appointments">
    <h2>Appointments</h2>
    <ul class="list-unstyled">
      <% @patient.appointments.each do |appointment| %>
        <% doctor = Doctor.find_by(id: appointment.doctor_id) %>
        <li>Dr. <%= appointment.doctor.first_name %> <%= appointment.doctor.last_name %> for <%= appointment.test.name %> on <%= appointment.date %> at <%= appointment.time.to_formatted_s(:time) %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/doctors/_form.html.erb
<%= form_for @doctor, html: { multipart: true } do |form| %>

  <div class="form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :specialty %>
    <%= form.text_field :specialty, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :new_patients %>
    <%= form.text_field :new_patients, class: "form-control" %>
  </div>

<%= form.submit class: "btn btn-success" %>
<% end %>

app/views/doctors/index.html.erb
<h3 class="page-header">
  Find a Doctor Today!
 </h3>

<div class="row">
	<% @doctors.each do |doctor| %>
		<div class="col-sm-6 col-md-4">
   			<div class="thumbnail">
				<%= link_to image_tag(doctor.image, width: "200"), doctor_url(doctor) %>
				<div class="caption">
					<h3><%= link_to doctor.last_name, doctor %></h3>
					<p><strong>Specialty:</strong> <%= doctor.specialty %></p>
					<p><strong>Accepting New Patients:</strong> <%= doctor.new_patients %></p>
				</div>
			</div>
		</div>
	<% end %>
</div>


			<%#= link_to "Edit", edit_doctor_url(doctor), class: 'btn-sm btn-danger' %>
			<%#= link_to "Delete", doctor_url(doctor), method: :delete, class: 'btn-sm btn-danger', data: {confirm: 'Seriously?'} %>
		

app/views/doctors/show.html.erb
<h1 class="title">
  Dr. <%= @doctor.first_name%> <%= @doctor.last_name%>
</h1>

<div class="row">
  <div class="col-md-6 summary">
    <h2>Summary</h2>
    <p><strong>Specialty:</strong> <%= @doctor.specialty %></p>
    <p><strong>Education:</strong> <%= @doctor.education %></p>
    <p><strong>Accepting New Patients:</strong> <%= @doctor.new_patients %></p>
  </div>
  <div class="col-md-6 appointments">
    <%= link_to "Book an Appointment", new_appointment_path, class: 'btn btn-sm btn-success' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Welcome to DocApp!</title>
  <%= javascript_include_tag 'application' %>

  <!-- Logo Font -->
    <link href="//fonts.googleapis.com/css?family=Righteous" rel="stylesheet" type="text/css">
    
  <!-- Bootstrap -->
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

  <!-- Font Awesome -->
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container">

      <!-- Alerts -->
      <% if notice %>
        <div class="alert alert-success" role="alert"><%= notice %></div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger" role="alert"><%= alert %></div>
      <% end %>
      
      <nav class="navbar navbar-inverse" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <!-- Rails equivalent to -->
          <!-- <a href="/" class="navbar-brand">Buyflix</a> -->
          <%= link_to "DocApp", doctors_path, class: "navbar-brand" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li>
              <a href="/">
                <i class="fa fa-home"></i>
                Home
              </a>
            </li>
            <li>
             <%= link_to "New Patient", new_patient_path %>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            
  <!-- Admin Menu -->
            <% if current_patient.try(:admin?) %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                <i class="fa fa-cog"></i>
                Admin
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "New Doctor", new_doctor_path %></li>
                <li><%= link_to "All Patients", patients_path %></li>
                <li><%= link_to "All Appointments", appointments_path %></li>
              </ul>
            </li>
              <% end %>

            
            <% if current_patient %>
              <li><%= link_to current_patient.try(:first_name), patient_url(current_patient) %></li>
              <li><%= link_to "Logout", logout_url %></li>
            <% else %>
              <li><%= link_to "Sign In", new_session_url %></li>
              <% end %>

          </ul>
        </div>
      </nav>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/patients/index.html.erb
<h3 class="page-header">
  All Patients
 </h3>

<ul>
	<% @patients.each do |patient| %>
			<li>
			<p><strong> Patient Name: </strong><%= link_to patient.last_name, patient_url(patient) %></p>
					<%= link_to "Edit", edit_patient_url(patient), class: 'btn-sm btn-danger' %>
					<%= link_to "Delete", patient_url(patient), method: :delete, class: 'btn-sm btn-danger', data: {confirm: 'Seriously?'} %>
			</li><br>
	<% end %>
</ul>

app/views/patients/new.html.erb
<!-- 
  Finish the signup form
  Validate that the email, password, and name are present
-->

<% if @patient.errors.any? %>

<div class="alert alert-danger" role="alert">
  <% @patient.errors.full_messages.each do |message| %>
    <%= message %><br>
    <% end %>
  </div>
  <% end %>

<%= form_for @patient do |form| %>
  <div class="form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :gender %>
    <%= form.text_field :gender, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :marital_status %>
    <%= form.text_field :marital_status, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :blood_type %>
    <%= form.text_field :blood_type, class: "form-control" %>
  </div>
  <%= form.button 'Sign Up', class: "btn btn-success" %>
<% end %>

app/views/patients/show.html.erb
<h1 class="title">
  <%= @patient.first_name%> <%= @patient.last_name%>
</h1>

<div class="row">
  <div class="col-md-6 summary">
    <h2>Summary</h2>
    <p><strong>Gender:</strong> <%= @patient.gender %></p>
    <p><strong>Marital Status:</strong> <%= @patient.marital_status %></p>
    <p><strong>Blood Type:</strong> <%= @patient.blood_type %></p>
  </div>
  <div class="col-md-6 appointments">
    <h2>Appointments</h2>
    <ul class="list-unstyled">
      <% @patient.appointments.each do |appointment| %>
        <% doctor = Doctor.find_by(id: appointment.doctor_id) %>
        <li>Dr. <%= appointment.doctor.last_name %> for <%= appointment.test.name %> on <%= appointment.date %> at <%= appointment.time.to_formatted_s(:time) %> <%= link_to "Update", edit_appointment_url(appointment), class: 'btn btn-sm btn-primary' %> <%= link_to "Delete", appointment_url(appointment), method: :delete, class: 'btn btn-sm btn-danger', data: {confirm: 'Seriously?'} %>
        <br><br>
        </li>
    <% end %>

<br>
<%= link_to "Book a New Appointment", new_appointment_path, class: 'btn btn-sm btn-success' %>

    </ul>
  </div>
</div>